import type { Metadata } from "next";
import SocialFollow from "../SocialFollow";
import ConsultationActions from "../ConsultationActions";
import { pageMetadata } from "../seo";

export const metadata: Metadata = pageMetadata({
  title: "Internal Medicine Services in Bhiwadi",
  description: "Explore Internal Medicine consultation, chronic disease care, medical weight management, preventive assessment, diagnostic guidance and follow-up services from Dr. Kulwant Yadav.",
  path: "/services",
});

const services = [
  { n:"01", id:"internal-medicine", title:"Internal medicine consultation", lead:"For adults with new, recurring or complex medical concerns.", body:"A comprehensive consultation brings together current symptoms, previous illnesses, medicines, lifestyle, examination and existing reports. Internal Medicine is especially useful when symptoms involve more than one body system or the next step is unclear.", includes:["Detailed symptom and medical-history review","Medication and previous-report review","Focused clinical examination","Assessment plan, treatment priorities and referral when required"], status:"Available as a core clinical service" },
  { n:"02", id:"chronic-disease", title:"Chronic disease management", lead:"For diabetes, hypertension, fatty liver, kidney risk and connected conditions.", body:"Long-term conditions often influence one another. Follow-up focuses on agreed targets, medicine safety, complications, lifestyle barriers and how changes in one condition affect the others.", includes:["Diabetes and blood-pressure monitoring","Fatty liver and metabolic-risk review","Kidney-risk and medicine-safety assessment","Coordination when several chronic conditions coexist"], status:"Available within Internal Medicine scope" },
  { n:"03", id:"weight-management", title:"Medical weight management", lead:"Clinical assessment of weight, metabolic risk and associated disease.", body:"Medical weight care considers biology, medicines, sleep, eating patterns, mobility, mental wellbeing and complications. The focus is practical health improvement rather than blame or extreme short-term dieting.", includes:["Weight and metabolic history","Screening for related conditions","Individual nutrition, activity and sleep priorities","Discussion of evidence-based medical or specialist options when appropriate"], status:"Available after individual clinical assessment" },
  { n:"04", id:"preventive-health", title:"Preventive health and metabolic screening", lead:"Risk assessment based on age, history, symptoms and previous reports.", body:"Preventive evaluation is personalised. It does not mean ordering every available test. Screening is selected according to age, family history, tobacco or alcohol exposure, vaccination history, symptoms and existing risk.", includes:["Cardiometabolic risk review","Age- and risk-appropriate screening discussion","Vaccination and lifestyle review","Interpretation of previous screening results"], status:"Available; tests are selected individually" },
  { n:"05", id:"ecg", title:"ECG", lead:"A recording of the heart’s electrical activity.", body:"An electrocardiogram may help assess heart rhythm, conduction patterns and certain signs of heart strain or injury. It may be advised for chest symptoms, palpitations, fainting, breathlessness, medicine monitoring or cardiovascular-risk evaluation.", includes:["Clinical decision on whether an ECG is appropriate","Interpretation in the context of symptoms and examination","Emergency or cardiology referral when findings require it","Explanation of the report and next step"], status:"On-site availability, equipment location and reporting arrangement must be confirmed before booking" },
  { n:"06", id:"echocardiography", title:"Echocardiography", lead:"An ultrasound examination that evaluates heart structure and function.", body:"Echocardiography may be advised for selected murmurs, breathlessness, swelling, suspected heart-function changes or abnormal examination and ECG findings. It is not automatically required for every BP, diabetes or chest-symptom consultation.", includes:["Assessment of whether echocardiography is clinically indicated","Coordination with an appropriate diagnostic facility or specialist","Review of a completed report in the wider clinical context","Cardiology referral when specialised imaging or treatment is needed"], status:"Whether Dr. Yadav performs, supervises or directly reports echocardiography—and where it is available—must be confirmed before publication" },
  { n:"07", id:"report-review", title:"Report review and follow-up", lead:"Follow-up after blood tests, imaging or treatment initiation.", body:"A report should be interpreted alongside the question that led to the test. Follow-up reviews progress, explains results, checks medicine response and decides whether treatment, monitoring or referral should change.", includes:["Blood-test and imaging review","Response and side-effect assessment","Updated treatment and monitoring plan","Referral or further testing only when clinically justified"], status:"Available as part of planned consultation follow-up" },
  { n:"08", id:"teleconsultation", title:"Teleconsultation", lead:"Remote consultation requires an approved clinical and operational workflow.", body:"Teleconsultation should be offered only after the doctor approves consent, patient identification, suitability screening, documentation, privacy, payment, emergency escalation, prescription and follow-up processes. Remote care is not appropriate for every symptom or emergency.", includes:["Patient identification and informed consent","Private, documented clinical interaction","Clear limits on examination and prescribing","Escalation to in-person or emergency care when necessary"], status:"Not currently confirmed or available through this website" },
];

export default function ServicesPage(){return <main className="services-page">
  <div className="info-strip"><span>Internal Medicine services · Bhiwadi</span><strong>Medical emergency? Visit the nearest emergency department.</strong></div>
  <header className="site-header"><a className="brand" href="/"><span className="brand-mark">KY</span><span><strong>Dr. Kulwant Yadav</strong><small>Consultant Internal Medicine</small></span></a><nav><a href="/">Home</a><a href="/about-dr-kulwant-yadav">About</a><a href="/conditions">Conditions</a><a href="/services">Services</a><a href="/health-library">Health library</a></nav><a href="/#appointment" className="header-cta">Book appointment</a></header>
  <section className="services-hero"><p className="eyebrow"><span/> Services</p><h1>Clinical services built around <em>careful decisions.</em></h1><p>From a first consultation to long-term follow-up, each service begins with the clinical question and the patient’s wider health—not a one-size-fits-all test package.</p><div className="service-jump">{services.map(s=><a key={s.id} href={`/services/${s.id}`}><span>{s.n}</span>{s.title}</a>)}</div></section>
  <section className="service-principles"><div><strong>Internal Medicine first</strong><p>Assessment and coordination across adult medical conditions.</p></div><div><strong>Tests with a purpose</strong><p>Diagnostics are advised when they can answer a clinical question.</p></div><div><strong>Referral when needed</strong><p>Specialist or emergency escalation remains part of safe care.</p></div></section>
  <section className="services-list">{services.map(service=><article className="service-detail" id={service.id} key={service.id}><div className="service-heading"><span>{service.n}</span><h2>{service.title}</h2><p>{service.lead}</p><a className="service-detail-link" href={`/services/${service.id}`}>View service details <b>→</b></a></div><div className="service-body"><p>{service.body}</p><h3>What this may include</h3><ul>{service.includes.map(item=><li key={item}>{item}</li>)}</ul><div className={`service-status ${service.id==="teleconsultation"||service.id==="echocardiography"||service.id==="ecg"?"verify":""}`}><span>{service.id==="teleconsultation"?"Current status":"Availability"}</span><strong>{service.status}</strong></div></div></article>)}</section>
  <section className="diagnostic-note"><div><p className="eyebrow"><span/> A note about diagnostics</p><h2>A test is useful when it changes a decision.</h2></div><p>ECG and echocardiography do not replace clinical assessment, and a normal result may not exclude every condition. Availability and reporting responsibility should be confirmed at the time of booking. Urgent symptoms should be assessed in an emergency setting rather than delayed for a routine diagnostic appointment.</p></section>
  <ConsultationActions tone="navy" />
  <section className="medical-disclaimer"><strong>Important information</strong><p>Service availability, appointment timings, fees, diagnostic location and reporting arrangements must be confirmed directly with the clinic. Website information does not replace individual medical assessment.</p></section>
  <footer><div className="footer-main"><a className="brand footer-brand" href="/"><span className="brand-mark">KY</span><span><strong>Dr. Kulwant Yadav</strong><small>Consultant Internal Medicine</small></span></a><p>Evidence-based adult medical care in Bhiwadi.</p></div><div className="footer-links"><div><strong>Explore</strong><a href="/about-dr-kulwant-yadav">About Dr. Yadav</a><a href="/conditions">Conditions</a><a href="/services">Services</a></div><div><strong>Important</strong><a href="/policies#medical-disclaimer">Medical disclaimer</a><a href="/#contact">Clinic information</a><a href="/#appointment">Appointments</a></div></div><SocialFollow/><small>© {new Date().getFullYear()} Dr. Kulwant Yadav. Information is educational and does not replace an individual consultation.</small></footer>
</main>}
