import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { createClient } from "@/lib/supabase/server";
import { StatusBadge } from "@/components/admin/StatusBadge";
import { RegistrationActions } from "@/components/admin/RegistrationActions";
import { Empty, PageHead, Pagination } from "../free-camp-registrations/page";

export default async function RegularPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  await requireAdmin();const p=await searchParams;const page=Math.max(1,Number(p.page)||1),size=20;const supabase=await createClient();let query=supabase.from("regular_registrations").select("id,consultation_type,preferred_date,source,registration_status,confirmation_status,created_at,patients(full_name,phone,city,area)",{count:"exact"}).order("created_at",{ascending:false}).range((page-1)*size,page*size-1);if(p.status)query=query.eq("registration_status",p.status);if(p.confirmation)query=query.eq("confirmation_status",p.confirmation);const{data,count}=await query;const rows=(data||[]).filter((r:any)=>!p.q||`${r.patients?.full_name} ${r.patients?.phone} ${r.id}`.toLowerCase().includes(p.q.toLowerCase()));
  return <><PageHead title="Regular registrations" subtitle="Consultations, appointments and follow-ups." exportType="regular"/><form className="admin-filters"><input name="q" placeholder="Search name, phone or ID"/><select name="status"><option value="">All statuses</option>{["New","Contacted","Confirmed","Appointment Booked","Completed","Cancelled","No-show"].map(x=><option key={x}>{x}</option>)}</select><select name="confirmation"><option value="">All confirmations</option><option>Pending</option><option>Confirmed</option><option>Rejected</option></select><button>Apply filters</button><Link href="/admin/regular-registrations">Clear filters</Link></form><div className="admin-table-wrap">{rows.length===0?<Empty text="No regular registrations match these filters."/>:<table className="admin-table"><thead><tr><th>Patient</th><th>Phone</th><th>Consultation</th><th>Preferred date</th><th>Source</th><th>Status</th><th>Confirmation</th><th>Created</th><th>Actions</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><strong>{r.patients?.full_name}</strong><small>{r.patients?.area||r.patients?.city}</small></td><td>{r.patients?.phone}</td><td>{r.consultation_type}</td><td>{r.preferred_date||"—"}</td><td>{r.source}</td><td><StatusBadge value={r.registration_status}/></td><td><StatusBadge value={r.confirmation_status}/></td><td>{new Date(r.created_at).toLocaleDateString("en-IN")}</td><td><RegistrationActions id={r.id} type="regular"/></td></tr>)}</tbody></table>}</div><Pagination page={page} pages={Math.max(1,Math.ceil((count||0)/size))}/></>;
}
