"use client";

import { useEffect, useState, type ChangeEvent, type FormEvent } from "react";
import Image from "next/image";
import Link from "next/link";
import { Activity, ArrowRight, ArrowUpRight, Droplets, Eye, HeartPulse, Scale, ShieldCheck, Stethoscope } from "lucide-react";
import JsonLd from "../../JsonLd";
import SiteFooter from "../../SiteFooter";
import { breadcrumbSchema, physicianId, siteUrl } from "../../seo";
import "./diabetes-overview.css";

type Language = "en" | "hi";
type Unit = "metric" | "imperial";
type Measure = "cm" | "kg" | "ft" | "inch" | "lb";
const appointmentUrl = "/book-appointment";
const phoneUrl = "tel:+919205775932";
const whatsappUrl = `https://wa.me/919205775932?text=${encodeURIComponent("Hello, I would like to request a diabetes consultation with Dr. Kulwant Yadav. Please share the available appointment timings.")}`;

const copy = {
  en: {
    emergency: "Severe symptoms? Seek emergency care rather than waiting for an appointment.",
    role: "Consultant in Internal Medicine", menu: "Website menu", language: "Page language", home: "Home", conditions: "Conditions", about: "About", library: "Health library", book: "Book appointment", mobileBook: "Book consultation", whatsapp: "WhatsApp", call: "Call",
    heroTag: "Diabetes care · Bhiwadi, Rajasthan", heroTitle: "Your Sugar, Your Choice", heroBody: "Understand blood sugar and make informed choices for everyday care.", heroCta: "Book consultation", heroSecond: "Explore the guide", doctorLine: "Dr. Kulwant Yadav · Gopinath Hospital, Bhiwadi", offerLabel: "Diabetes care package includes", offerItems: ["Nerve test – Vibrasense", "ECG", "Detailed diabetic consultation"],
    nav: "Explore this page", navLinks: [["BMI", "#bmi"], ["Symptoms", "#symptoms"], ["Your numbers", "#numbers"], ["Indian meals", "#food"], ["Next steps", "#support"]],
    bmiTag: "01 / A starting point", bmiCardTitle: "Check your Body Mass Index (BMI)", bmiCardHelp: "A useful starting point—not a diagnosis.", bmiTitle: "Check your BMI. Keep it in context.", bmiIntro: "Body Mass Index (BMI) compares weight with height. It can start a conversation about metabolic health, but it cannot diagnose diabetes or describe your health on its own.", metric: "Metric", imperial: "Feet & pounds", heightCm: "Height (cm)", weightKg: "Weight (kg)", heightFt: "Height (feet)", heightIn: "Extra inches", weightLb: "Weight (lb)", calculate: "Calculate BMI", bmiResult: "Your BMI estimate", bmiUnit: "kg/m²", bmiLow: "Below the WHO adult reference range", bmiReference: "Within the WHO adult reference range", bmiElevated: "Above the WHO adult reference range", bmiHigh: "In a higher WHO adult BMI range", bmiError: "Enter realistic height and weight values in every field.", bmiPrivacy: "Calculated only on this device. Your measurements are not sent or saved.", bmiCaution: "For adults only. BMI does not measure body fat directly; pregnancy, muscle mass and South Asian ancestry can change how a result should be interpreted. Ask a clinician about your individual risk.", bmiScale: ["<18.5", "18.5–24.9", "25–29.9", "30+"],
    symptomsTag: "02 / Notice, then assess", symptomsTitle: "Symptoms and risk factors are not the same thing.", symptomsIntro: "Symptoms are changes you may notice. Risk factors are things that can make type 2 diabetes more likely. Symptoms alone cannot diagnose diabetes, and diabetes may occur without noticeable symptoms.", symptomsLabel: "Possible symptoms", riskLabel: "Common type 2 risk factors", symptoms: ["More thirst than usual", "Passing urine often", "Unusual tiredness", "Blurred vision", "Unexplained weight loss", "Slow-healing wounds or repeated infections"], risks: ["A family history of type 2 diabetes", "Less physical activity", "Excess weight, especially around the waist", "Diabetes during a previous pregnancy"], symptomsFoot: "A blood test and clinical assessment—not a symptom checklist—help establish what is happening.",
    linkTag: "03 / Connected health", linkTitle: "Diabetes and weight influence each other.", linkBody: "Type 2 diabetes is not a matter of willpower. Changes in how the body uses insulin, family history, activity, sleep, medicines and weight can all matter. A plan should address the person, not one number.", linkCards: [["Start with what is manageable", "Food, activity and sleep changes work best when they fit real life."], ["Know when to seek advice", "A clinician can decide whether tests, medicines or more support may help."], ["Keep following up", "Blood sugar, blood pressure and kidney health deserve attention together."]],
    numbersTag: "04 / Know your ABCs", numbersTitle: "Three measures worth discussing.", numbersIntro: "These are conversation starters, not universal targets. Your doctor can interpret reports and set goals that fit your situation.", numbers: [["A · HbA1c", "An estimate of average blood glucose over about three months. It may be unreliable in some conditions."], ["B · Blood pressure", "A useful measure of strain on the heart and blood vessels; your target is individual."], ["C · Cholesterol", "A blood test that helps assess cardiovascular risk alongside glucose and blood pressure."]], numbersCta: "Discuss your reports",
    foodTag: "05 / Everyday Indian meals", foodTitle: "Keep familiar food. Build a more balanced plate.", foodIntro: "Roti, rice, dal, vegetables, curd and fruit can fit into an individual meal plan. Amounts, timing and food choices should reflect your medicines, work schedule, preferences and other health conditions. No one needs to assume they must completely stop rice or roti.", plateLabel: "Illustrative balanced plate—not a prescription", plateHalf: "½ plate", plateHalfText: "Non-starchy vegetables: sabzi, salad, leafy greens", plateQuarter: "¼ plate", plateQuarterText: "Protein: dal, beans, curd, paneer, egg or fish", plateCarb: "¼ plate", plateCarbText: "Roti or rice; consider fibre-rich choices and portions", foodNote: "Choose water instead of sugary drinks more often. Whole fruit has fibre and is generally more filling than juice; portion and timing still matter.",
    healthTag: "06 / Beyond glucose", healthTitle: "Care looks beyond one reading.", healthIntro: "Diabetes can affect several parts of the body over time. Regular assessment can help your care team notice changes and decide what follow-up is useful.", health: [["Heart & blood pressure", "Review blood pressure and cholesterol as part of cardiovascular care."], ["Kidneys", "Blood and urine tests may identify kidney changes before symptoms appear."], ["Eyes & feet", "Ask when eye and foot checks are right for you."]],
    supportTag: "Your next step", supportTitle: "Get guidance that fits your life.", supportBody: "Bring recent reports, medicine names and your questions. Dr. Yadav can help you interpret the results and plan appropriate follow-up at Gopinath Hospital, Bhiwadi.", supportCta: "Request an appointment", supportWhatsApp: "Ask on WhatsApp", supportNote: "An appointment is confirmed only when the clinic replies. Do not wait for a routine visit if you have confusion, fainting, persistent vomiting, deep rapid breathing or low glucose that is not improving; seek urgent care.",
    resourcesTitle: "Helpful reading", resources: [["When to consult a physician", "/health-library/diabetes-when-to-consult-a-physician"], ["High blood pressure care", "/conditions/hypertension"], ["Fatty liver and metabolic health", "/conditions/fatty-liver-masld"]], sourcesTitle: "Medical sources", disclaimer: "This page is for general education, not diagnosis or a personal treatment plan. The new content has not yet been separately marked as reviewed by Dr. Yadav. Discuss your results and treatment with a qualified healthcare professional.",
  },
  hi: {
    emergency: "गंभीर लक्षण हों तो अपॉइंटमेंट का इंतज़ार न करें—आपातकालीन चिकित्सा लें।",
    role: "आंतरिक चिकित्सा सलाहकार", menu: "वेबसाइट मेन्यू", language: "पेज की भाषा", home: "होम", conditions: "स्वास्थ्य विषय", about: "डॉक्टर के बारे में", library: "स्वास्थ्य जानकारी", book: "अपॉइंटमेंट लें", mobileBook: "परामर्श बुक करें", whatsapp: "व्हाट्सऐप", call: "कॉल करें",
    heroTag: "मधुमेह देखभाल · भिवाड़ी, राजस्थान", heroTitle: "आपकी शुगर, आपका चुनाव", heroBody: "रक्त शर्करा को समझें और रोज़मर्रा की देखभाल के लिए सोच-समझकर कदम चुनें।", heroCta: "परामर्श बुक करें", heroSecond: "जानकारी देखें", doctorLine: "डॉ. कुलवंत यादव · गोपीनाथ अस्पताल, भिवाड़ी", offerLabel: "मधुमेह देखभाल पैकेज में शामिल", offerItems: ["नसों की जाँच – Vibrasense", "ECG", "विस्तृत मधुमेह परामर्श"],
    nav: "इस पेज पर", navLinks: [["BMI", "#bmi"], ["लक्षण", "#symptoms"], ["जाँचें", "#numbers"], ["भोजन", "#food"], ["अगला कदम", "#support"]],
    bmiTag: "01 / शुरुआत", bmiCardTitle: "अपना बॉडी मास इंडेक्स (BMI) जाँचें", bmiCardHelp: "बातचीत की शुरुआत—निदान नहीं।", bmiTitle: "अपना BMI जानें। इसे सही संदर्भ में समझें।", bmiIntro: "बॉडी मास इंडेक्स (BMI) में वजन की तुलना लंबाई से की जाती है। यह चयापचय सेहत पर बातचीत शुरू कर सकता है, लेकिन अकेले इससे मधुमेह का निदान या पूरी सेहत का आकलन नहीं होता।", metric: "सेंटीमीटर और किलो", imperial: "फुट और पाउंड", heightCm: "लंबाई (सेमी)", weightKg: "वजन (किलो)", heightFt: "लंबाई (फुट)", heightIn: "अतिरिक्त इंच", weightLb: "वजन (पाउंड)", calculate: "BMI निकालें", bmiResult: "आपका अनुमानित BMI", bmiUnit: "किलो/मी²", bmiLow: "WHO की वयस्क संदर्भ सीमा से नीचे", bmiReference: "WHO की वयस्क संदर्भ सीमा में", bmiElevated: "WHO की वयस्क संदर्भ सीमा से ऊपर", bmiHigh: "WHO की ऊँची वयस्क BMI सीमा में", bmiError: "हर खाने में वास्तविक लंबाई और वजन दर्ज करें।", bmiPrivacy: "गणना केवल आपके उपकरण पर होती है। आपकी जानकारी भेजी या सहेजी नहीं जाती।", bmiCaution: "केवल वयस्कों के लिए। BMI शरीर की चर्बी सीधे नहीं मापता। गर्भावस्था, मांसपेशियों की मात्रा और दक्षिण एशियाई पृष्ठभूमि परिणाम का अर्थ बदल सकते हैं। व्यक्तिगत जोखिम के लिए डॉक्टर से बात करें।", bmiScale: ["<18.5", "18.5–24.9", "25–29.9", "30+"],
    symptomsTag: "02 / पहचानें, फिर जाँचें", symptomsTitle: "लक्षण और जोखिम के कारण अलग-अलग हैं।", symptomsIntro: "लक्षण वे बदलाव हैं जो आप महसूस कर सकते हैं। जोखिम के कारण टाइप 2 मधुमेह की संभावना बढ़ा सकते हैं। केवल लक्षणों से निदान नहीं होता; बिना स्पष्ट लक्षणों के भी मधुमेह हो सकता है।", symptomsLabel: "संभावित लक्षण", riskLabel: "टाइप 2 के सामान्य जोखिम कारक", symptoms: ["अधिक प्यास लगना", "बार-बार पेशाब आना", "असामान्य थकान", "धुंधला दिखाई देना", "बिना कारण वजन घटना", "घाव देर से भरना या बार-बार संक्रमण होना"], risks: ["परिवार में टाइप 2 मधुमेह", "शारीरिक गतिविधि कम होना", "अधिक वजन, विशेषकर कमर के आसपास", "पिछली गर्भावस्था में मधुमेह"], symptomsFoot: "क्या हो रहा है, यह समझने के लिए रक्त जाँच और चिकित्सकीय मूल्यांकन ज़रूरी हैं—सिर्फ लक्षणों की सूची नहीं।",
    linkTag: "03 / जुड़ी हुई सेहत", linkTitle: "मधुमेह और वजन एक-दूसरे को प्रभावित कर सकते हैं।", linkBody: "टाइप 2 मधुमेह केवल इच्छाशक्ति का मामला नहीं है। इंसुलिन का असर, पारिवारिक इतिहास, गतिविधि, नींद, दवाएँ और वजन—सब भूमिका निभा सकते हैं। योजना व्यक्ति के लिए होनी चाहिए, केवल एक संख्या के लिए नहीं।", linkCards: [["छोटे, संभव कदम", "भोजन, गतिविधि और नींद में वही बदलाव उपयोगी हैं जो दिनचर्या में निभ सकें।"], ["सलाह कब लें", "डॉक्टर तय कर सकते हैं कि कौन-सी जाँच, दवा या सहायता उचित हो सकती है।"], ["नियमित संपर्क रखें", "रक्त शर्करा, रक्तचाप और गुर्दों की सेहत को साथ देखना उपयोगी है।"]],
    numbersTag: "04 / अपनी अहम जाँचें", numbersTitle: "तीन माप जिन पर बात करना उपयोगी है।", numbersIntro: "ये बातचीत की शुरुआत हैं, सबके लिए एक जैसे लक्ष्य नहीं। डॉक्टर रिपोर्ट समझकर आपकी स्थिति के अनुसार लक्ष्य तय कर सकते हैं।", numbers: [["A · HbA1c", "लगभग तीन महीनों की औसत रक्त शर्करा का अनुमान। कुछ स्थितियों में यह कम भरोसेमंद हो सकता है।"], ["B · रक्तचाप", "दिल और रक्त वाहिकाओं पर दबाव समझने में मदद करता है; लक्ष्य व्यक्ति के अनुसार होता है।"], ["C · कोलेस्ट्रॉल", "रक्त शर्करा और रक्तचाप के साथ दिल की सेहत का जोखिम समझने में मदद करने वाली जाँच।"]], numbersCta: "अपनी रिपोर्ट पर बात करें",
    foodTag: "05 / घर का परिचित भोजन", foodTitle: "परिचित भोजन रखें। थाली में संतुलन लाएँ।", foodIntro: "रोटी, चावल, दाल, सब्ज़ी, दही और फल व्यक्तिगत भोजन योजना का हिस्सा हो सकते हैं। मात्रा और समय आपकी दवाओं, काम, पसंद और दूसरी बीमारियों के अनुसार तय हों। यह न मानें कि सभी को चावल या रोटी पूरी तरह छोड़नी होगी।", plateLabel: "संतुलित थाली का उदाहरण—व्यक्तिगत पर्चा नहीं", plateHalf: "½ थाली", plateHalfText: "कम स्टार्च वाली सब्ज़ियाँ: सब्ज़ी, सलाद, हरी पत्तियाँ", plateQuarter: "¼ थाली", plateQuarterText: "प्रोटीन: दाल, फलियाँ, दही, पनीर, अंडा या मछली", plateCarb: "¼ थाली", plateCarbText: "रोटी या चावल; रेशेदार विकल्प और मात्रा पर ध्यान दें", foodNote: "मीठे पेयों की जगह अक्सर पानी चुनें। पूरे फल में रेशा होता है और वह जूस से अधिक पेट भरता है; मात्रा और समय फिर भी मायने रखते हैं।",
    healthTag: "06 / शर्करा से आगे", healthTitle: "देखभाल केवल एक रीडिंग तक सीमित नहीं है।", healthIntro: "समय के साथ मधुमेह शरीर के कई हिस्सों को प्रभावित कर सकता है। नियमित मूल्यांकन बदलाव जल्दी पहचानने और सही फ़ॉलो-अप चुनने में मदद करता है।", health: [["दिल और रक्तचाप", "दिल की सेहत के लिए रक्तचाप और कोलेस्ट्रॉल की समीक्षा करें।"], ["गुर्दे", "खून और पेशाब की जाँच लक्षणों से पहले बदलाव दिखा सकती है।"], ["आँखें और पैर", "पूछें कि आँखों और पैरों की जाँच आपके लिए कब उचित है।"]],
    supportTag: "अगला कदम", supportTitle: "अपनी दिनचर्या के अनुरूप सलाह लें।", supportBody: "हाल की रिपोर्ट, दवाओं के नाम और अपने सवाल साथ लाएँ। डॉ. यादव रिपोर्ट समझने और गोपीनाथ अस्पताल, भिवाड़ी में उचित फ़ॉलो-अप की योजना बनाने में मदद कर सकते हैं।", supportCta: "अपॉइंटमेंट का अनुरोध करें", supportWhatsApp: "व्हाट्सऐप पर पूछें", supportNote: "क्लिनिक के उत्तर के बाद ही अपॉइंटमेंट पक्का माना जाए। भ्रम, बेहोशी, लगातार उल्टी, गहरी तेज़ साँस या कम रक्त शर्करा का न सुधरना हो तो नियमित अपॉइंटमेंट का इंतज़ार न करें—तुरंत चिकित्सा लें।",
    resourcesTitle: "आगे पढ़ें", resources: [["मधुमेह में डॉक्टर से कब मिलें", "/health-library/diabetes-when-to-consult-a-physician"], ["उच्च रक्तचाप की देखभाल", "/conditions/hypertension"], ["फैटी लिवर और चयापचय सेहत", "/conditions/fatty-liver-masld"]], sourcesTitle: "चिकित्सा स्रोत", disclaimer: "यह पेज सामान्य शिक्षा के लिए है, निदान या व्यक्तिगत इलाज की योजना नहीं। नए पाठ को अभी अलग से डॉ. यादव द्वारा समीक्षा-प्राप्त नहीं बताया गया है। अपनी रिपोर्ट और इलाज पर योग्य चिकित्सक से बात करें।",
  },
} as const;

const sources = [
  ["WHO — BMI and weight", "https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight"],
  ["NIDDK — BMI and health", "https://www.niddk.nih.gov/health-information/weight-management/adult-overweight-obesity/am-i-healthy-weight"],
  ["NIDDK — Diabetes tests", "https://www.niddk.nih.gov/health-information/diabetes/overview/tests-diagnosis"],
  ["NIDDK — Healthy living", "https://www.niddk.nih.gov/health-information/diabetes/overview/healthy-living-with-diabetes"],
] as const;

function BmiCalculator({ t }: { t: typeof copy[Language] }) {
  const [unit, setUnit] = useState<Unit>("metric");
  const [measure, setMeasure] = useState<Record<Measure, string>>({ cm: "", kg: "", ft: "", inch: "", lb: "" });
  const [bmi, setBmi] = useState<number | null>(null);
  const [error, setError] = useState("");
  const update = (field: Measure) => (event: ChangeEvent<HTMLInputElement>) => {
    setMeasure(current => ({ ...current, [field]: event.target.value }));
    setBmi(null);
    setError("");
  };
  const switchUnit = (next: Unit) => { setUnit(next); setBmi(null); setError(""); };
  const calculate = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const cm = Number(measure.cm), kg = Number(measure.kg), ft = Number(measure.ft), inch = Number(measure.inch), lb = Number(measure.lb);
    const valid = unit === "metric" ? cm >= 90 && cm <= 250 && kg >= 20 && kg <= 350 : Number.isInteger(ft) && ft >= 3 && ft <= 8 && Number.isInteger(inch) && inch >= 0 && inch < 12 && lb >= 44 && lb <= 770 && measure.inch.trim() !== "";
    if (!valid) { setBmi(null); setError(t.bmiError); return; }
    const value = unit === "metric" ? kg / ((cm / 100) ** 2) : 703.06958 * lb / ((ft * 12 + inch) ** 2);
    if (!Number.isFinite(value) || value < 8 || value > 80) { setBmi(null); setError(t.bmiError); return; }
    setBmi(value);
    setError("");
  };
  const resultLabel = bmi === null ? "" : bmi < 18.5 ? t.bmiLow : bmi < 25 ? t.bmiReference : bmi < 30 ? t.bmiElevated : t.bmiHigh;
  const marker = bmi === null ? 0 : Math.min(100, Math.max(0, ((bmi - 14) / 26) * 100));
  return <form className="db2-bmi-card" onSubmit={calculate} noValidate>
    <div className="db2-bmi-card-top"><div><Scale size={25} aria-hidden="true" /><h2>{t.bmiCardTitle}</h2><p>{t.bmiCardHelp}</p></div><div className="db2-unit-switch" role="group" aria-label={t.metric}><button type="button" aria-pressed={unit === "metric"} onClick={() => switchUnit("metric")}>{t.metric}</button><button type="button" aria-pressed={unit === "imperial"} onClick={() => switchUnit("imperial")}>{t.imperial}</button></div></div>
    <div className="db2-bmi-fields">{unit === "metric" ? <><label>{t.heightCm}<input type="number" inputMode="decimal" min="90" max="250" step="0.1" value={measure.cm} onChange={update("cm")} placeholder="168" required /></label><label>{t.weightKg}<input type="number" inputMode="decimal" min="20" max="350" step="0.1" value={measure.kg} onChange={update("kg")} placeholder="68" required /></label></> : <><label>{t.heightFt}<input type="number" inputMode="numeric" min="3" max="8" step="1" value={measure.ft} onChange={update("ft")} placeholder="5" required /></label><label>{t.heightIn}<input type="number" inputMode="numeric" min="0" max="11" step="1" value={measure.inch} onChange={update("inch")} placeholder="6" required /></label><label>{t.weightLb}<input type="number" inputMode="decimal" min="44" max="770" step="0.1" value={measure.lb} onChange={update("lb")} placeholder="150" required /></label></>}</div>
    {error && <p className="db2-bmi-error" role="alert">{error}</p>}
    <button className="db2-button db2-bmi-submit" type="submit">{t.calculate}<ArrowRight size={18} aria-hidden="true" /></button>
    {bmi !== null && <div className="db2-bmi-result" aria-live="polite"><span>{t.bmiResult}</span><strong>{bmi.toFixed(1)} <small>{t.bmiUnit}</small></strong><p>{resultLabel}</p><div className="db2-bmi-scale" aria-hidden="true"><span style={{ left: `${marker}%` }} /></div><div className="db2-bmi-scale-labels" aria-hidden="true">{t.bmiScale.map(label => <small key={label}>{label}</small>)}</div></div>}
    <small className="db2-bmi-privacy"><ShieldCheck size={15} aria-hidden="true" />{t.bmiPrivacy}</small>
  </form>;
}

export default function DiabetesOverviewPage() {
  const [language, setLanguage] = useState<Language>("en");
  const t = copy[language];
  useEffect(() => {
    document.documentElement.lang = language === "hi" ? "hi-IN" : "en-IN";
    return () => { document.documentElement.lang = "en-IN"; };
  }, [language]);
  const schema = [
    { "@context": "https://schema.org", "@type": "MedicalWebPage", name: "Diabetes Care in Bhiwadi", description: "Patient education about diabetes, BMI and ways to request an Internal Medicine consultation.", url: `${siteUrl}/conditions/diabetes`, about: { "@type": "MedicalCondition", name: "Diabetes mellitus" }, mentions: { "@id": physicianId }, inLanguage: ["en-IN", "hi-IN"] },
    breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Conditions", path: "/conditions" }, { name: "Diabetes", path: "/conditions/diabetes" }]),
  ];
  const healthIcons = [HeartPulse, Droplets, Eye];
  return <main className="diabetes-page db2">
    <JsonLd data={schema} />
    <div className="info-strip"><span>{t.heroTag}</span><strong>{t.emergency}</strong></div>
    <header className="site-header"><Link className="brand" href="/"><span className="brand-mark">KY</span><span><strong>{language === "hi" ? "डॉ. कुलवंत यादव" : "Dr. Kulwant Yadav"}</strong><small>{t.role}</small></span></Link><nav aria-label={t.nav}><Link href="/conditions">{t.conditions}</Link><Link href="/about-dr-kulwant-yadav">{t.about}</Link><Link href="/health-library">{t.library}</Link></nav><Link className="header-cta" href={appointmentUrl}>{t.book}</Link><details className="db2-mobile-menu"><summary><span className="db2-menu-lines" aria-hidden="true"><span /><span /><span /></span><span className="db2-visually-hidden">{t.menu}</span></summary><nav aria-label={t.nav}><Link href="/">{t.home}</Link><Link href="/conditions">{t.conditions}</Link><Link href="/about-dr-kulwant-yadav">{t.about}</Link><Link href="/health-library">{t.library}</Link><Link href={appointmentUrl}>{t.book}</Link></nav></details></header>
    <div className="db2-language" role="group" aria-label={t.language}><span>{t.language}</span><button type="button" lang="en" aria-pressed={language === "en"} onClick={() => setLanguage("en")}>English</button><button type="button" lang="hi" aria-pressed={language === "hi"} onClick={() => setLanguage("hi")}>हिंदी</button></div>

    <section className="db2-hero"><Image src="/diabetes-care-hero-original.png" alt="An adult at home after a walk, holding a water bottle" fill priority sizes="100vw" /><div className="db2-hero-shade" /><div className="db2-hero-content"><p className="db2-eyebrow">{t.heroTag}</p><h1>{t.heroTitle}</h1><p>{t.heroBody}</p><div className="db2-hero-actions"><Link className="db2-button db2-button-light db2-offer-cta" href={appointmentUrl}><span>{t.heroCta}</span><ArrowRight size={18} aria-hidden="true" /></Link><a href="#bmi">{t.heroSecond} ↓</a></div><div className="db2-offer-includes"><strong>{t.offerLabel}</strong><ul>{t.offerItems.map(item => <li key={item}>{item}</li>)}</ul></div><span className="db2-doctor-line"><Stethoscope size={18} aria-hidden="true" />{t.doctorLine}</span><Link className="db2-mobile-hero-cta" href={appointmentUrl}>{t.heroCta}<ArrowRight size={18} aria-hidden="true" /></Link></div></section>

    <section className="db2-section db2-bmi-section" id="bmi"><BmiCalculator t={t} /><div className="db2-bmi-copy"><div><p className="db2-eyebrow">{t.bmiTag}</p><h2>{t.bmiTitle}</h2><p>{t.bmiIntro}</p></div><div className="db2-bmi-context"><Activity size={25} aria-hidden="true" /><p>{t.bmiCaution}</p></div></div></section>
    <nav className="db2-index" aria-label={t.nav}><strong>{t.nav}</strong><div>{t.navLinks.map(([label, href]) => <a href={href} key={href}>{label}</a>)}</div></nav>

    <section className="db2-section db2-symptoms" id="symptoms"><div className="db2-section-heading"><p className="db2-eyebrow">{t.symptomsTag}</p><h2>{t.symptomsTitle}</h2><p>{t.symptomsIntro}</p></div><div className="db2-symptom-grid"><article><span>01</span><h3>{t.symptomsLabel}</h3><ul>{t.symptoms.map(item => <li key={item}>{item}</li>)}</ul></article><article><span>02</span><h3>{t.riskLabel}</h3><ul>{t.risks.map(item => <li key={item}>{item}</li>)}</ul></article></div><p className="db2-section-note">{t.symptomsFoot}</p></section>

    <section className="db2-section db2-connection"><div className="db2-section-heading"><p className="db2-eyebrow">{t.linkTag}</p><h2>{t.linkTitle}</h2><p>{t.linkBody}</p></div><div className="db2-connection-grid">{t.linkCards.map(([title, body], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="db2-section db2-numbers" id="numbers"><div className="db2-section-heading"><p className="db2-eyebrow">{t.numbersTag}</p><h2>{t.numbersTitle}</h2><p>{t.numbersIntro}</p></div><div className="db2-numbers-grid">{t.numbers.map(([title, body], i) => <article key={title}><span>{["A", "B", "C"][i]}</span><h3>{title}</h3><p>{body}</p></article>)}</div><Link className="db2-text-link" href={appointmentUrl}>{t.numbersCta}<ArrowUpRight size={17} aria-hidden="true" /></Link></section>

    <section className="db2-section db2-food" id="food"><div className="db2-section-heading"><p className="db2-eyebrow">{t.foodTag}</p><h2>{t.foodTitle}</h2><p>{t.foodIntro}</p></div><div className="db2-food-layout"><div className="db2-plate" role="img" aria-label={`${t.plateHalfText}; ${t.plateQuarterText}; ${t.plateCarbText}`}><Image src="/diabetes-balanced-indian-plate.png" alt="" fill sizes="(max-width: 600px) 90vw, 520px" /><div className="db2-plate-half"><span>{t.plateHalf}</span><strong>{t.plateHalfText}</strong></div><div className="db2-plate-quarters"><div><span>{t.plateQuarter}</span><strong>{t.plateQuarterText}</strong></div><div><span>{t.plateCarb}</span><strong>{t.plateCarbText}</strong></div></div></div><div className="db2-food-copy"><strong>{t.plateLabel}</strong><p>{t.foodNote}</p></div></div></section>

    <section className="db2-section db2-health"><div className="db2-section-heading"><p className="db2-eyebrow">{t.healthTag}</p><h2>{t.healthTitle}</h2><p>{t.healthIntro}</p></div><div className="db2-health-grid">{t.health.map(([title, body], i) => { const Icon = healthIcons[i]; return <article key={title}><Icon size={27} aria-hidden="true" /><h3>{title}</h3><p>{body}</p></article>; })}</div></section>

    <section className="db2-support" id="support"><div className="db2-support-photo"><Image src="/dr-kulwant-yadav-portrait.png" alt="Dr. Kulwant Yadav, Consultant in Internal Medicine" fill sizes="(max-width: 700px) 100vw, 35vw" /></div><div className="db2-support-copy"><p className="db2-eyebrow">{t.supportTag}</p><h2>{t.supportTitle}</h2><p>{t.supportBody}</p><div className="db2-support-actions"><Link className="db2-button db2-button-light" href={appointmentUrl}>{t.supportCta}<ArrowRight size={18} aria-hidden="true" /></Link><a href={whatsappUrl} target="_blank" rel="noopener noreferrer">{t.supportWhatsApp}<ArrowUpRight size={16} aria-hidden="true" /></a></div><small>{t.supportNote}</small></div></section>

    <section className="db2-section db2-resources"><h2>{t.resourcesTitle}</h2><div className="db2-resource-grid">{t.resources.map(([title, href]) => <Link href={href} key={href}>{title}<ArrowUpRight size={17} aria-hidden="true" /></Link>)}</div><details><summary>{t.sourcesTitle}</summary><ul>{sources.map(([name, href]) => <li key={href}><a href={href} target="_blank" rel="noopener noreferrer">{name} ↗</a></li>)}</ul></details><p className="db2-disclaimer">{t.disclaimer}</p></section>
    <SiteFooter reviewed={false} language={language} />
    <nav className="db2-mobile-actions" aria-label={t.book}><Link href={appointmentUrl}>{t.mobileBook}</Link><a href={whatsappUrl} target="_blank" rel="noopener noreferrer">{t.whatsapp}</a><a href={phoneUrl}>{t.call}</a></nav>
  </main>;
}
