import type { Metadata } from "next";
import SocialFollow from "../SocialFollow";
import ConsultationActions from "../ConsultationActions";
import { pageMetadata } from "../seo";

export const metadata:Metadata=pageMetadata({
  title:"Internal Medicine Clinic in Bhiwadi",
  description:"Visit Dr. Kulwant Yadav, Honorary Consultant in Internal Medicine at Gopinath Hospital, H-226 Industrial Area, Bhiwadi, Rajasthan.",
  path:"/clinic-bhiwadi",
});

const services=["Internal Medicine consultation","Diabetes and blood-pressure management","Chronic disease follow-up","Fatty liver and metabolic assessment","Medical weight-management consultation","Kidney-risk and abnormal-report review","Respiratory and infection assessment","Preventive health evaluation","Follow-up and report review"];
const faqs=[
  ["Where is the clinic located?","Gopinath Hospital, H-226, Industrial Area, near Ramphal Cinema, Bhiwadi – 301019, District Alwar, Rajasthan."],
  ["What are the consultation timings?","Please call or WhatsApp +91 92057 75932 for current consultation timings and same-day availability before travelling."],
  ["Is an appointment required?","An appointment request is recommended. It becomes confirmed only after the clinic responds with an available date and time."],
  ["Can I visit for diabetes and blood pressure together?","Yes. Both can be reviewed within Internal Medicine, including their connected heart and kidney risks."],
  ["Are ECG and echocardiography available at this location?","On-site equipment, operating arrangement and reporting responsibility have not yet been confirmed. Ask the clinic before booking a diagnostic visit."],
  ["Is parking or wheelchair access available?","Parking, lift, wheelchair route and accessible washroom information must be checked at the physical clinic before publication."],
];

export default function ClinicPage(){return <main className="clinic-page">
  <div className="info-strip"><span>Clinic information · Bhiwadi</span><strong>Medical emergency? Visit the nearest emergency department.</strong></div>
  <header className="site-header"><a className="brand" href="/"><span className="brand-mark">KY</span><span><strong>Dr. Kulwant Yadav</strong><small>Consultant Internal Medicine</small></span></a><nav><a href="/">Home</a><a href="/about-dr-kulwant-yadav">About</a><a href="/conditions">Conditions</a><a href="/services">Services</a><a href="/clinic-bhiwadi">Clinic</a></nav><a href="/book-appointment" className="header-cta">Book appointment</a></header>
  <section className="clinic-hero"><div><p className="eyebrow"><span/> Gopinath Hospital · Bhiwadi</p><h1>Internal Medicine consultations in <em>Bhiwadi.</em></h1><p>Adult medical consultations, chronic-disease management and preventive community-health initiatives with Dr. Kulwant Yadav.</p><div className="clinic-role"><span>Role</span><strong>Dr. Kulwant Yadav</strong><small>Honorary Consultant Internal Medicine</small></div></div><div className="clinic-photo"><img src="/dr-kulwant-yadav-portrait.png" alt="Dr. Kulwant Yadav, Consultant in Internal Medicine in Bhiwadi"/></div></section>
  <section className="verification-banner"><strong>Call before travelling</strong><p>Consultation timings may change. Call or WhatsApp <a href="tel:+919205775932">+91 92057 75932</a> to confirm availability and your appointment before visiting.</p></section>
  <section className="clinic-facts section" id="clinic-details"><div><p className="section-label"><span>01</span> Clinic details</p><h2>Plan your visit to Gopinath Hospital.</h2><p>Internal Medicine consultations and community preventive-health initiatives are supported at this Bhiwadi affiliation.</p></div><dl><div><dt>Clinic name</dt><dd>Gopinath Hospital</dd></div><div><dt>Doctor’s role</dt><dd>Dr. Kulwant Yadav · Honorary Consultant Internal Medicine</dd></div><div><dt>Full address</dt><dd>H-226, Industrial Area, Bhiwadi – 301019, District Alwar, Rajasthan</dd></div><div><dt>Nearby landmark</dt><dd>Near Ramphal Cinema</dd></div><div><dt>Consultation days and hours</dt><dd>Call for current timings and availability</dd></div><div><dt>Phone & WhatsApp</dt><dd><a href="tel:+919205775932">+91 92057 75932</a></dd></div></dl></section>
  <section className="map-section" id="directions"><a className="map-placeholder" href="https://maps.app.goo.gl/W9QHHQxRkA5bGasi7" target="_blank" rel="noopener noreferrer"><span>Google Maps</span><strong>Gopinath Hospital, Bhiwadi</strong><p>Open the verified map location for live navigation and route details.</p></a><div className="directions-copy"><p className="section-label light"><span>02</span> Directions</p><h2>Travelling to the clinic</h2><p>Use the Google Maps link for current turn-by-turn navigation. The clinic is in the Industrial Area, near Ramphal Cinema.</p><div className="direction-list"><div><span>Landmark</span><small>Near Ramphal Cinema</small></div><div><span>Locality</span><small>Industrial Area, Bhiwadi</small></div><div><span>Postal code</span><small>301019</small></div></div><a className="primary-button" href="https://maps.app.goo.gl/W9QHHQxRkA5bGasi7" target="_blank" rel="noopener noreferrer">Get directions <span>↗</span></a></div></section>
  <section className="clinic-services section"><div className="section-label"><span>03</span> Services at this location</div><div className="clinic-services-head"><h2>Adult medical care, with availability confirmed at booking.</h2><p>Consultation services may be offered at this practice. Diagnostic equipment and on-site procedures require separate confirmation.</p></div><div className="clinic-service-grid">{services.map((service,index)=><div key={service}><span>{String(index+1).padStart(2,"0")}</span><strong>{service}</strong></div>)}</div><p className="verification-note">ECG and echocardiography should not be represented as on-site services until equipment, location and reporting arrangements are verified.</p></section>
  <section className="visit-info section"><div><p className="section-label light"><span>04</span> Appointment instructions</p><h2>Request first. Travel after confirmation.</h2><ol><li><span>1</span><p>Submit a request with a broad reason and preferred date.</p></li><li><span>2</span><p>Wait for the clinic to confirm the appointment time and location.</p></li><li><span>3</span><p>Bring medicine names, previous prescriptions and relevant reports.</p></li><li><span>4</span><p>Seek emergency care instead if symptoms are severe or life-threatening.</p></li></ol><a href="/book-appointment" className="primary-button">Request appointment <span>→</span></a></div><div className="access-card"><span>Access and arrival</span><h3>Details awaiting a physical-site check</h3><ul><li>Parking location and charges</li><li>Step-free or wheelchair route</li><li>Lift availability</li><li>Accessible washroom</li><li>Drop-off point</li><li>Floor and clinic entrance signage</li></ul></div></section>
  <section className="clinic-faq section"><div className="section-label"><span>05</span> Local FAQs</div><div className="faq-grid"><h2>Before you travel.</h2><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
  <ConsultationActions tone="teal" />
  <section className="section outreach-section"><div><p className="section-label"><span>06</span> Clinical affiliations & community outreach</p><h2>Expanding access to preventive and chronic care.</h2></div><div><h3>Honorary Consultant Internal Medicine</h3><p>At Gopinath Hospital, Dr. Yadav supports access to specialised internal medicine care and chronic disease management for the broader community.</p><p>He also helps organise preventive screening initiatives, including advanced FibroScan camps and comprehensive Senior Care Metabolic Shield programs for early disease detection and practical lifestyle intervention.</p></div></section>
  <footer><div className="footer-main"><a className="brand footer-brand" href="/"><span className="brand-mark">KY</span><span><strong>Dr. Kulwant Yadav</strong><small>Consultant Internal Medicine</small></span></a><p>Evidence-based adult medical care in Bhiwadi.</p></div><div className="footer-links"><div><strong>Clinic</strong><a href="#clinic-details">Clinic details</a><a href="#directions">Directions</a><a href="/book-appointment">Book appointment</a></div><div><strong>Explore</strong><a href="/conditions">Conditions</a><a href="/services">Services</a><a href="/about-dr-kulwant-yadav">About Dr. Yadav</a></div></div><SocialFollow/><small>© {new Date().getFullYear()} Dr. Kulwant Yadav. Do not travel until the clinic confirms your appointment and location.</small></footer>
</main>}
