import Link from "next/link";
import { requireAdmin } from "@/lib/admin/auth";
import { createClient } from "@/lib/supabase/server";
import { StatusBadge } from "@/components/admin/StatusBadge";
import { RegistrationActions } from "@/components/admin/RegistrationActions";

export default async function CampRegistrationsPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  await requireAdmin(); const p=await searchParams; const page=Math.max(1,Number(p.page)||1); const size=20; const supabase=await createClient();
  let query=supabase.from("camp_registrations").select("id, created_at, confirmation_status, reminder_status, attendance_status, source, patients(full_name,phone,age,area,city), camps(name), camp_sessions(session_date)",{count:"exact"}).order("created_at",{ascending:false}).range((page-1)*size,page*size-1);
  if(p.confirmation)query=query.eq("confirmation_status",p.confirmation); if(p.attendance)query=query.eq("attendance_status",p.attendance); if(p.reminder)query=query.eq("reminder_status",p.reminder); if(p.source)query=query.eq("source",p.source);
  const {data,count,error}=await query; const pages=Math.max(1,Math.ceil((count||0)/size));
  const filtered=(data||[]).filter((r:any)=>!p.q||`${r.patients?.full_name} ${r.patients?.phone} ${r.patients?.area} ${r.camps?.name} ${r.id}`.toLowerCase().includes(p.q.toLowerCase()));
  return <><PageHead title="Free camp registrations" subtitle="Manage confirmations, reminders and attendance." exportType="camp"/><Filters/><div className="admin-table-wrap">{error?<Empty text="Could not load registrations."/>:filtered.length===0?<Empty text="No camp registrations match these filters."/>:<table className="admin-table"><thead><tr><th>Patient</th><th>Phone</th><th>Age / Area</th><th>Camp / Sunday</th><th>Registration</th><th>Confirmation</th><th>Reminder</th><th>Attendance</th><th>Actions</th></tr></thead><tbody>{filtered.map((r:any)=><tr key={r.id}><td><strong>{r.patients?.full_name}</strong></td><td>{r.patients?.phone}</td><td>{r.patients?.age||"—"}<small>{r.patients?.area||r.patients?.city||"—"}</small></td><td>{r.camps?.name}<small>{r.camp_sessions?.session_date?new Date(`${r.camp_sessions.session_date}T00:00:00`).toLocaleDateString("en-IN",{dateStyle:"medium"}):"Not selected"}</small></td><td>{new Date(r.created_at).toLocaleDateString("en-IN")}<small>{r.source}</small></td><td><StatusBadge value={r.confirmation_status}/></td><td><StatusBadge value={r.reminder_status}/></td><td><StatusBadge value={r.attendance_status}/></td><td><RegistrationActions id={r.id} type="camp"/></td></tr>)}</tbody></table>}</div><Pagination page={page} pages={pages}/></>;
}

function Filters(){return <form className="admin-filters"><input name="q" placeholder="Search name, phone, area or ID"/><select name="confirmation"><option value="">All confirmations</option><option>Pending</option><option>Confirmed</option><option>Rejected</option></select><select name="reminder"><option value="">All reminders</option><option>Not Scheduled</option><option>Scheduled</option><option>Sent</option><option>Failed</option></select><select name="attendance"><option value="">All attendance</option><option>Pending</option><option>Attended</option><option>No-show</option><option>Cancelled</option></select><button>Apply filters</button><Link href="/admin/free-camp-registrations">Clear filters</Link></form>}
export function PageHead({title,subtitle,exportType}:{title:string;subtitle:string;exportType?:string}){return <div className="admin-page-heading"><div><p>Patient CRM</p><h1>{title}</h1><span>{subtitle}</span></div>{exportType&&<a className="admin-secondary-button" href={`/api/admin/export?type=${exportType}`}>Export CSV</a>}</div>}
export function Empty({text}:{text:string}){return <div className="admin-empty"><strong>Nothing to show</strong><p>{text}</p></div>}
export function Pagination({page,pages}:{page:number;pages:number}){return <nav className="admin-pagination"><Link aria-disabled={page<=1} href={`?page=${Math.max(1,page-1)}`}>Previous</Link><span>Page {page} of {pages}</span><Link aria-disabled={page>=pages} href={`?page=${Math.min(pages,page+1)}`}>Next</Link></nav>}
